// error

func test(_ x: Int) {
    x = 4 + x
}